---
title: "AviationWeather"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r library load}
library(tidyverse)
library(XML)
library(xml2)
library(plyr)
```

```{r}
metar_xml_url <- "https://www.aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=xml&stationString=KPAE&hoursBeforeNow=4"

metar_xml_read <- read_xml(metar_xml_url)

metar_xml <- xmlTreeParse(metar_xml_read, useInternalNodes = TRUE)

metar_xml_root <- xmlRoot(metar_xml)

metar_as_list <- xmlToList(metar_xml_root)

metar_as_list_dd <- metar_as_list[["data"]][grep("METAR", names(metar_as_list[["data"]]))]

list_to_data_frame_func <- function(x){
  output_final <- data.frame(matrix(ncol = length(x[[1]][1:17]), nrow = length(x)), stringsAsFactors = FALSE)
  colnames(output_final) <- names(x[[1]][1:17])
  for(i in 1:length(x)){
    output_final[i,] <- t(x[[i]][1:17])
  } 
  output_final
} 

metar_adjusted <- list_to_data_frame_func(metar_as_list_dd)

metar_adjusted
```

```{r}
taf_read <- read_csv2("https://www.aviationweather.gov/adds/dataserver_current/httpparam?dataSource=tafs&requestType=retrieve&format=csv&stationString=KDEN&hoursBeforeNow=2", skip = 4)

column_count <- str_split(taf_read[[1]][1],",")

taf_df <- as.data.frame(str_split_fixed(taf[[1]], ",", n = length(column_count[[1]])), stringsAsFactors = FALSE)

colnames(taf_df) <- taf_df[1,1:306]

taf_df <- taf_df[-1,]
taf_df <- taf_df[,-307]

```